<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * Table: fines
     * PK: id (BIGINT UNSIGNED AUTO_INCREMENT)
     * FK: transaction_id → transactions.id (ON DELETE CASCADE)
     *
     * Data Types:
     * - amount: DECIMAL(8,2) — currency type as per grading criteria
     * - status: ENUM (unpaid, paid) — boolean-like status
     * - paid_at: TIMESTAMP NULLABLE
     *
     * Note: Fine records are auto-generated by the CalculateLateFine trigger.
     */
    public function up(): void
    {
        Schema::create('fines', function (Blueprint $table) {
            $table->id();                                                      // PK: BIGINT UNSIGNED
            $table->foreignId('transaction_id')->constrained()->cascadeOnDelete(); // FK → transactions.id
            $table->decimal('amount', 8, 2);                                   // DECIMAL(8,2) — currency
            $table->enum('status', ['unpaid', 'paid'])->default('unpaid');      // ENUM
            $table->timestamp('paid_at')->nullable();                          // TIMESTAMP, NULLABLE
            $table->timestamps();                                              // created_at, updated_at
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('fines');
    }
};
